package com.sg.plmadapter.windchill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-10-29T15:14:04.308+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://pm.webservice.integration.tmt.ext/", name = "PMWebservice")
@XmlSeeAlso({ObjectFactory.class})
public interface PMWebservice {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://pm.webservice.integration.tmt.ext/PMWebservice/createFolderRequest", output = "http://pm.webservice.integration.tmt.ext/PMWebservice/createFolderResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://pm.webservice.integration.tmt.ext/PMWebservice/createFolder/Fault/Exception")})
    @RequestWrapper(localName = "createFolder", targetNamespace = "http://pm.webservice.integration.tmt.ext/", className = "com.sg.plmadapter.windchill.CreateFolder")
    @WebMethod
    @ResponseWrapper(localName = "createFolderResponse", targetNamespace = "http://pm.webservice.integration.tmt.ext/", className = "com.sg.plmadapter.windchill.CreateFolderResponse")
    public int createFolder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://pm.webservice.integration.tmt.ext/PMWebservice/deleteFolderRequest", output = "http://pm.webservice.integration.tmt.ext/PMWebservice/deleteFolderResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://pm.webservice.integration.tmt.ext/PMWebservice/deleteFolder/Fault/Exception")})
    @RequestWrapper(localName = "deleteFolder", targetNamespace = "http://pm.webservice.integration.tmt.ext/", className = "com.sg.plmadapter.windchill.DeleteFolder")
    @WebMethod
    @ResponseWrapper(localName = "deleteFolderResponse", targetNamespace = "http://pm.webservice.integration.tmt.ext/", className = "com.sg.plmadapter.windchill.DeleteFolderResponse")
    public int deleteFolder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://pm.webservice.integration.tmt.ext/PMWebservice/editFolderRequest", output = "http://pm.webservice.integration.tmt.ext/PMWebservice/editFolderResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://pm.webservice.integration.tmt.ext/PMWebservice/editFolder/Fault/Exception")})
    @RequestWrapper(localName = "editFolder", targetNamespace = "http://pm.webservice.integration.tmt.ext/", className = "com.sg.plmadapter.windchill.EditFolder")
    @WebMethod
    @ResponseWrapper(localName = "editFolderResponse", targetNamespace = "http://pm.webservice.integration.tmt.ext/", className = "com.sg.plmadapter.windchill.EditFolderResponse")
    public int editFolder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;
}
