
package com.sg.plmadapter.windchill;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-10-29T15:14:04.121+08:00
 * Generated source version: 3.0.0
 * 
 */
public final class PMWebservice_PMWebservicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://pm.webservice.integration.tmt.ext/", "PMWebserviceService");

    private PMWebservice_PMWebservicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PMWebserviceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PMWebserviceService ss = new PMWebserviceService(wsdlURL, SERVICE_NAME);
        PMWebservice port = ss.getPMWebservicePort();  
        
        {
        System.out.println("Invoking createFolder...");
        java.util.List<java.lang.String> _createFolder_arg0 = null;
        try {
            int _createFolder__return = port.createFolder(_createFolder_arg0);
            System.out.println("createFolder.result=" + _createFolder__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteFolder...");
        java.lang.String _deleteFolder_arg0 = "";
        try {
            int _deleteFolder__return = port.deleteFolder(_deleteFolder_arg0);
            System.out.println("deleteFolder.result=" + _deleteFolder__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking editFolder...");
        java.lang.String _editFolder_arg0 = "";
        java.lang.String _editFolder_arg1 = "";
        try {
            int _editFolder__return = port.editFolder(_editFolder_arg0, _editFolder_arg1);
            System.out.println("editFolder.result=" + _editFolder__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
