package com.sg.plmadapter.windchill;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.14
 * 2014-10-29T16:28:56.726+08:00
 * Generated source version: 2.6.14
 * 
 */
@WebServiceClient(name = "PMWebserviceService", 
                  wsdlLocation = "http://10.99.190.133/Windchill/servlet/PMWebservice?wsdl",
                  targetNamespace = "http://pm.webservice.integration.tmt.ext/") 
public class PMWebserviceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pm.webservice.integration.tmt.ext/", "PMWebserviceService");
    public final static QName PMWebservicePort = new QName("http://pm.webservice.integration.tmt.ext/", "PMWebservicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://lcy.yaozheng.com/Windchill/servlet/PMWebservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PMWebserviceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.99.190.133/Windchill/servlet/PMWebservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PMWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PMWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PMWebserviceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PMWebserviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PMWebserviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PMWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PMWebservice
     */
    @WebEndpoint(name = "PMWebservicePort")
    public PMWebservice getPMWebservicePort() {
        return super.getPort(PMWebservicePort, PMWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PMWebservice
     */
    @WebEndpoint(name = "PMWebservicePort")
    public PMWebservice getPMWebservicePort(WebServiceFeature... features) {
        return super.getPort(PMWebservicePort, PMWebservice.class, features);
    }

}
